[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "haveno-client"
description = "A client for interacting with the Haveno daemon."
readme = "README.md"
license = { file = "LICENSE" }
authors = [ { name = "Kewbit", email = "support@haveno.app" } ]
keywords = ["haveno", "monero", "p2p", "exchange"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
]

# Runtime dependencies (only what end users need at install time)
dependencies = [
  "grpcio",
  "socks",
  "protobuf"
]

[project.optional-dependencies]
# Dev tools you don't want installed for end users by default
codegen = ["grpcio-tools"]

[project.urls]
Homepage = "https://haveno.app"
Repository = "https://git.haveno.app/haveno-network/python-haveno-client"
Issues = "https://git.haveno.app/haveno-network/python-haveno-client/issues"
Documentation = "https://haveno.app/documentation"
Changelog = "https://haveno.app/changelog"
Funding = "https://haveno.app/donate"

[project.scripts]
haveno-client = "haveno_client.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["haveno_client*"]

[tool.setuptools]
include-package-data = true
